#!/usr/bin/env bash
# =============================================================================
# nginx-config.sh — Generate and install Nginx reverse proxy config
#
# Usage: bash nginx-config.sh <subdomain> <port> <project-name>
# Example: bash nginx-config.sh myapp 3007 my-app
#
# Generates config at: /etc/nginx/sites-available/<subdomain>.iacomtata.com.br
# Enables via symlink to: /etc/nginx/sites-enabled/
# =============================================================================

set -euo pipefail

# --- Configuration ---
VPS_IP="76.13.175.161"
VPS_USER="root"
VPS_SSH="${VPS_USER}@${VPS_IP}"
DOMAIN="iacomtata.com.br"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[AVISO]${NC} $1"; }
log_error() { echo -e "${RED}[ERRO]${NC} $1"; }

# --- Validate arguments ---
if [[ $# -lt 3 ]]; then
    echo "Uso: bash nginx-config.sh <subdominio> <porta> <nome-projeto>"
    echo "Exemplo: bash nginx-config.sh myapp 3007 my-app"
    exit 1
fi

SUBDOMAIN="$1"
PORT="$2"
PROJECT_NAME="$3"
FULL_DOMAIN="${SUBDOMAIN}.${DOMAIN}"
CONFIG_FILE="/etc/nginx/sites-available/${FULL_DOMAIN}"
ENABLED_LINK="/etc/nginx/sites-enabled/${FULL_DOMAIN}"

log_info "Gerando configuracao Nginx para ${FULL_DOMAIN} -> 127.0.0.1:${PORT}"

# Generate the Nginx config
# This template handles:
# - HTTP to HTTPS redirect (after SSL is configured)
# - WebSocket upgrade support (for Socket.IO apps)
# - Proxy headers for correct IP forwarding
# - Static file caching
# - Gzip compression
NGINX_CONFIG="# Nginx config for ${PROJECT_NAME}
# Generated by skill-deploy-vps on $(date +%Y-%m-%d)
# Domain: ${FULL_DOMAIN} -> 127.0.0.1:${PORT}

server {
    listen 80;
    listen [::]:80;
    server_name ${FULL_DOMAIN};

    # Proxy all traffic to the Node.js app
    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \"upgrade\";

        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Disable buffering for streaming/SSE
        proxy_buffering off;
        proxy_cache_bypass \$http_upgrade;
    }

    # Static file caching (if app serves static files)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_set_header Host \$host;
        expires 7d;
        add_header Cache-Control \"public, immutable\";
    }

    # Health check endpoint
    location /health {
        proxy_pass http://127.0.0.1:${PORT}/health;
        proxy_set_header Host \$host;
        access_log off;
    }

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;
}"

# Upload and install config on VPS
log_info "Instalando configuracao no servidor..."

# Write config to VPS
echo "$NGINX_CONFIG" | ssh "${VPS_SSH}" "cat > ${CONFIG_FILE}"

# Enable the site
ssh "${VPS_SSH}" "ln -sf ${CONFIG_FILE} ${ENABLED_LINK}"

# Test Nginx config
log_info "Testando configuracao Nginx..."
NGINX_TEST=$(ssh "${VPS_SSH}" "nginx -t 2>&1")
if echo "$NGINX_TEST" | grep -q "successful"; then
    log_ok "Configuracao Nginx valida"
else
    log_error "Erro na configuracao Nginx:"
    echo "$NGINX_TEST"
    log_warn "Revertendo configuracao..."
    ssh "${VPS_SSH}" "rm -f ${ENABLED_LINK}"
    exit 1
fi

# Reload Nginx
log_info "Recarregando Nginx..."
ssh "${VPS_SSH}" "systemctl reload nginx"
log_ok "Nginx recarregado — ${FULL_DOMAIN} ativo (HTTP)"
log_info "Execute ssl-setup.sh para ativar HTTPS"
